### ISSUE TITLE
想问一下，envoy-go-extension只支持http协议吗

### ISSUE THREAD

**Issue by ResolveWang** [mosn/envoy-go-extension#67]
如题，想问一下，envoy-go-extension只支持http吗，如果我想处理tcp的数据流，这个扩展能做吗

**Comment by antJack** [comment]
目前只支持 http 协议，我们最近也正在[开源 envoy L4 扩展](https://github.com/envoyproxy/envoy/issues/25906)，届时将能够处理任意 tcp 数据流

**Comment by ResolveWang** [comment]
好的，谢谢解答
